global:
  scrape_interval: 5s   # 데이터 수집 최소 간격

# 메트릭 수집 대상

scrape_configs:
  - job_name: 'node-exporter'

    # 컨테이너(task) 단위로 수집

    dockerswarm_sd_configs:   
      - host: unix:///var/run/docker.sock
        role: tasks
        
    # 컨테이너의 IP 대신 호스트 IP를 스크랩

    relabel_configs:
      - source_labels: [__meta_dockerswarm_node_address]
        target_label: __address__
        replacement: $1:9100